version: "3"

services:
  app:
    image: simplycodedsoftware/php:8.3.10
    volumes:
      - "$PWD:/data/app"
    user: 1000:1000
    container_name: "es-domain"
    working_dir: "/data/app"
    command: sleep 999999
    environment:
      DATABASE_DSN: pgsql://ecotone:secret@database:5432/ecotone
    networks:
      - default
  database:
    image: postgres:15
    networks:
      - default
    environment:
      POSTGRES_USER: "ecotone"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"